"use client";

import { useEffect, useState } from "react";

type Lang = "tj" | "ru" | "en";

const content = {
  tj: {
    nav: ["Дар бораи ман", "Таҷриба", "Малакаҳо", "Лоиҳаҳо", "Тамос"], talk: "Тамос гиред",
    location: "Душанбе, Тоҷикистон", title: "Муҳандиси инфрасохтори IT, DevOps, шабака ва AI",
    lead: "Ман системаҳои боэътимод месозам, ки инфрасохтор, одамон ва технологияҳои зеҳниро ба ҳам мепайванданд.", view: "Дидани таҷриба", contact: "Тамос",
    stats: ["Камера насб шудааст", "Стансияи дурдаст", "Шкафи серверӣ"],
    sections: ["01 — Дар бораи ман", "02 — Таҷриба", "03 — Малакаҳо", "04 — Лоиҳаҳои интихобшуда", "05 — Соҳибкорӣ", "06 — Таҳсилот"],
    profileTitle: "Технология бояд мушкили воқеиро ҳал кунад, на ин ки корро душвортар созад.",
    profile: ["Ман мутахассиси инфрасохтор ва системаҳои IT бо таҳсилоти Амнияти иттилоотӣ ҳастам. Фаъолияти ман шабакаҳо, Linux, камераҳои назоратӣ, автоматизатсия ва зеҳни сунъиро бо корҳои воқеӣ мепайвандад.", "Аз таҷҳизоти саҳроӣ ва шабакаҳои хусусӣ то хизматрасониҳои Docker ва ёрдамчиёни зеҳнӣ — ман системаҳои фаҳмо, идорашаванда ва омода барои васеъшавиро месозам."],
    available: "Барои ҳамкории байналмилалӣ ва шарикии техникӣ омодаам", current: "Ҳоло", operations: "IT ва амалиёти техникӣ · Инфрасохтор", scale: "Системаҳои саҳроӣ дар миқёси калон",
    expText: "Инфрасохтори камера, шабака ва Linux-ро аз шкафи физикӣ то идоракунии бехатари дурдаст насб, пайваст ва идора мекунам.",
    expList: ["1 350+ камераи CCTV насб ва танзим шудааст", "150+ стансия барои идоракунии дурдаст пайваст шудааст", "50+ шкафи серверӣ бо patch panel ва кабелгузории тоза", "Хонаи ҳушёр, мониторинг ва автоматизатсия"],
    expertiseTitle: "Дониши системавӣ — аз таҷҳизоти канорӣ то cloud.", expertiseText: "Маҷмӯи малакаҳои амалӣ, ки аз инфрасохтори воқеӣ ва ҳалли масъалаҳо ба даст омадааст.",
    skills: [["Инфрасохтор ва Linux", "Ubuntu, Docker, серверҳо, нусхаҳои эҳтиётӣ ва идоракунии боэътимоди дурдаст."], ["Шабака ва дастрасии бехатар", "MikroTik, APN-и хусусӣ, Headscale, Tailscale, VPN ва шабакаҳои PoE."], ["CCTV ва системаҳои саҳроӣ", "Dahua, Hikvision, PTZ, NVR, RTSP/ONVIF ва системаҳои 24/7."], ["AI ва автоматизатсия", "Python, FastAPI, n8n, Telegram, Ollama, PostgreSQL ва Redis."]],
    projects: [["CCTV ва инфрасохтори шаҳрӣ", "Системаҳои бузурги назорати видеоиро дар ҷойҳои ҷамъиятӣ, тиҷоратӣ ва хусусӣ насб, танзим ва дастгирӣ кардам.", "1 350+ камера"], ["Шабакаи стансияҳои дурдаст", "Барои стансияҳои Ubuntu, MikroTik, PoE ва PTZ дастрасии бехатар ва дастгирии марказонидашуда сохтам.", "150+ стансия"], ["Ёрдамчии NERU AI", "Ёрдамчии бисёрзабонаи таваққуфгоҳ бо Telegram, FastAPI ва AI-и маҳаллӣ.", "TJ · RU · EN · UZ"], ["Системаҳои хонаи ҳушёр", "Ҳалли амалӣ барои амният, мониторинг, идоракунии дурдаст ва автоматизатсияи ҳаррӯза.", "Аз оғоз то анҷом"], ["Шкафҳои серверӣ ва кабелгузорӣ", "Шкафҳои сервериро ҷамъ карда, patch panel ва кабелҳои тоза, нишондодашуда ва қулай барои хизматрасониро насб кардам.", "50+ шкаф"], ["Тиҷорати рақамӣ", "Серверу сомонаҳои шахсӣ, мағозаи камера ва компютер, инчунин фурӯш дар Alif Shop ва LakLak.", "Муассис ва роҳбар"]],
    businessTitle: "Ман ҳам система ва ҳам тиҷорат месозам.", business: ["Дар баробари корҳои инфрасохторӣ сервер ва чанд сомонаи худро идора мекунам. Мағозаи техникиам ба камераҳои 4G/Wi-Fi/CCTV, ноутбук ва компютерҳо машғул аст.", "Инчунин дар Alif Shop ва LakLak фаъолият карда, дониши техникиро бо тиҷорати электронӣ ва хизматрасонӣ ба муштариён якҷо мекунам."],
    cards: [["Таҳсилот", "Дипломи Амнияти иттилоотӣ", "Киберамният ва системаҳои иттилоотӣ"], ["Забонҳо", "Тоҷикӣ · Русӣ · Англисӣ", "Модарӣ · Касбӣ · Дар ҳоли омӯзиш"], ["Ҷойгиршавӣ", "Душанбе, Тоҷикистон", "Омода барои ҳамкории байналмилалӣ"]],
    contactKicker: "Биёед системаҳои боэътимод созем", contactTitle: "Масъалаи техникӣ доред, ки ҳалли он муҳим аст?", contactText: "Ба лоиҳаҳои инфрасохторӣ, табдили рақамӣ, автоматизатсияи AI ва рушди байналмилалӣ таваҷҷуҳ дорам.", call: "Занг"
  },
  ru: {
    nav: ["Обо мне", "Опыт", "Навыки", "Проекты", "Контакты"], talk: "Связаться",
    location: "Душанбе, Таджикистан", title: "Инженер IT-инфраструктуры, DevOps, сетей и AI",
    lead: "Я создаю надёжные системы, объединяющие инфраструктуру, людей и интеллектуальные технологии.", view: "Смотреть опыт", contact: "Контакты",
    stats: ["Установлено камер", "Удалённых станций", "Серверных шкафов"],
    sections: ["01 — Обо мне", "02 — Опыт", "03 — Навыки", "04 — Избранные проекты", "05 — Предпринимательство", "06 — Образование"],
    profileTitle: "Технологии должны решать реальные задачи, а не создавать лишнюю сложность.",
    profile: ["Я специалист по IT-инфраструктуре и системам с образованием в области информационной безопасности. Моя работа объединяет сети, Linux, видеонаблюдение, автоматизацию и AI с реальными операционными задачами.", "От полевого оборудования и частных сетей до Docker-сервисов и интеллектуальных помощников — я создаю понятные, обслуживаемые и масштабируемые системы."],
    available: "Открыт для международных проектов и технического партнёрства", current: "Сейчас", operations: "IT и технические операции · Инфраструктура", scale: "Полевые системы в большом масштабе",
    expText: "Устанавливаю, подключаю и управляю распределённой инфраструктурой камер, сетей и Linux — от физического шкафа до защищённого удалённого управления.",
    expList: ["Установлено и настроено 1 350+ CCTV-камер", "150+ станций подключено к удалённому управлению", "50+ серверных шкафов с patch panel и аккуратной коммутацией", "Умный дом, мониторинг и автоматизация"],
    expertiseTitle: "Системные знания — от периферии до облака.", expertiseText: "Практический набор навыков, сформированный реальной инфраструктурой и решением технических задач.",
    skills: [["Инфраструктура и Linux", "Ubuntu, Docker, серверы, резервное копирование и надёжное удалённое управление."], ["Сети и безопасный доступ", "MikroTik, частный APN, Headscale, Tailscale, VPN и PoE-сети."], ["CCTV и полевые системы", "Dahua, Hikvision, PTZ, NVR, RTSP/ONVIF и круглосуточные системы."], ["AI и автоматизация", "Python, FastAPI, n8n, Telegram, Ollama, PostgreSQL и Redis."]],
    projects: [["CCTV и городская инфраструктура", "Устанавливал, настраивал и поддерживал крупные системы видеонаблюдения на общественных, коммерческих и частных объектах.", "1 350+ камер"], ["Сеть удалённых станций", "Создал безопасный удалённый доступ и централизованную поддержку станций Ubuntu, MikroTik, PoE и PTZ.", "150+ станций"], ["AI-помощник NERU", "Собственный многоязычный парковочный помощник на Telegram, FastAPI и локальном AI.", "TJ · RU · EN · UZ"], ["Системы умного дома", "Практические решения для безопасности, мониторинга, удалённого управления и бытовой автоматизации.", "Под ключ"], ["Серверные шкафы и кабельные системы", "Собирал серверные шкафы, устанавливал patch panel и выполнял аккуратную, маркированную коммутацию.", "50+ шкафов"], ["Цифровой бизнес", "Собственный сервер и сайты, магазин камер и компьютеров, продажи через Alif Shop и LakLak.", "Основатель"]],
    businessTitle: "Я создаю не только системы, но и бизнес вокруг них.", business: ["Параллельно с инфраструктурной работой я управляю собственным сервером и несколькими сайтами, развиваю магазин камер 4G/Wi-Fi/CCTV, ноутбуков и компьютеров.", "Также продаю через Alif Shop и LakLak, объединяя техническую экспертизу, электронную коммерцию и работу с клиентами."],
    cards: [["Образование", "Диплом по информационной безопасности", "Кибербезопасность и информационные системы"], ["Языки", "Таджикский · Русский · Английский", "Родной · Профессиональный · Развивающийся"], ["Локация", "Душанбе, Таджикистан", "Открыт для международного сотрудничества"]],
    contactKicker: "Давайте строить надёжные системы", contactTitle: "Есть техническая задача, которую стоит решить?", contactText: "Мне интересны инфраструктура, цифровая трансформация, AI-автоматизация и международные проекты развития.", call: "Позвонить"
  },
  en: {
    nav: ["About", "Experience", "Expertise", "Projects", "Contact"], talk: "Let's talk", location: "Dushanbe, Tajikistan", title: "IT Infrastructure, DevOps, Network & AI Engineer", lead: "I build reliable systems that connect infrastructure, people and intelligent technology.", view: "View experience", contact: "Contact", stats: ["Cameras installed", "Remote stations", "Server cabinets"],
    sections: ["01 — Profile", "02 — Experience", "03 — Expertise", "04 — Selected work", "05 — Entrepreneurship", "06 — Credentials"], profileTitle: "Technology should solve real problems—not add complexity.", profile: ["I am an IT infrastructure and systems specialist with a degree in Information Security. My work sits where networks, Linux, CCTV, automation and AI meet real-world operations.", "From field equipment and private networks to Docker services and intelligent assistants, I focus on systems that are understandable, maintainable and ready to scale."], available: "Open to international opportunities and technical partnerships", current: "Current", operations: "IT & Technical Operations · Infrastructure", scale: "Field systems at scale", expText: "I install, connect and manage distributed camera, network and Linux infrastructure—from the physical cabinet to secure remote operations.", expList: ["1,350+ CCTV cameras installed and configured", "150+ stations connected for remote management", "50+ server cabinets with patch panels and clean cabling", "Smart home, monitoring and automation solutions"], expertiseTitle: "Systems knowledge, from edge to cloud.", expertiseText: "A practical toolkit shaped by production infrastructure and hands-on problem solving.",
    skills: [["Infrastructure & Linux", "Ubuntu, Docker, servers, backups and reliable remote operations."], ["Networks & Secure Access", "MikroTik, private APN, Headscale, Tailscale, VPN and PoE networks."], ["CCTV & Edge Systems", "Dahua, Hikvision, PTZ, NVR, RTSP/ONVIF and 24/7 field systems."], ["AI & Automation", "Python, FastAPI, n8n, Telegram, Ollama, PostgreSQL and Redis."]],
    projects: [["CCTV & City Infrastructure", "Installed, configured and supported large-scale CCTV systems across public, commercial and private locations.", "1,350+ cameras"], ["Remote Station Network", "Built secure remote access and centralized support for Ubuntu, MikroTik, PoE and PTZ-based field stations.", "150+ stations"], ["NERU AI Assistant", "A self-hosted multilingual parking assistant built with Telegram, FastAPI and local AI.", "TJ · RU · EN · UZ"], ["Smart Home Systems", "Designed practical smart-home solutions for security, monitoring, remote control and everyday automation.", "End-to-end delivery"], ["Server Racks & Structured Cabling", "Assembled server cabinets, installed patch panels and delivered clean, labeled and serviceable cable management.", "50+ cabinets"], ["Digital Business & E-commerce", "Run my own server and websites, a CCTV and computer equipment shop, and active storefronts on Alif Shop and LakLak.", "Founder & operator"]],
    businessTitle: "I build systems—and businesses around them.", business: ["Alongside infrastructure work, I operate my own server and several websites, and develop a technology shop focused on 4G/Wi-Fi/CCTV cameras, laptops and computers.", "I also sell through Alif Shop and LakLak, combining technical expertise with hands-on e-commerce and customer service."], cards: [["Education", "Degree in Information Security", "Cybersecurity & information systems"], ["Languages", "Tajik · Russian · English", "Native · Professional · Developing"], ["Location", "Dushanbe, Tajikistan", "Open to international collaboration"]], contactKicker: "Let's build reliable systems", contactTitle: "Have a technical challenge worth solving?", contactText: "I am interested in infrastructure, digital transformation, AI automation and international development projects.", call: "Call"
  }
} as const;

function Diagram() { return <div className="diagram" aria-hidden="true"><div className="grid"/><i className="route r1"/><i className="route r2"/><i className="route r3"/><b className="dot d1"/><b className="dot d2"/><b className="dot d3"/><b className="dot d4"/><div className="antenna"><em/><span/><span/></div><div className="rack">SERVER<i/><i/><i/><i/></div><div className="db">DATA</div><small>INFRASTRUCTURE / NETWORK / INTELLIGENCE</small></div>; }

export default function Home() {
  const [lang, setLang] = useState<Lang>("tj"); const t = content[lang];
  useEffect(() => { const saved = localStorage.getItem("portfolio-language") as Lang | null; if (saved && content[saved]) setLang(saved); }, []);
  const choose = (value: Lang) => { setLang(value); localStorage.setItem("portfolio-language", value); document.documentElement.lang = value === "tj" ? "tg" : value; };
  return <main id="top">
    <header><a className="brand" href="#top">ZAFARI HAKIMJON</a><nav>{t.nav.map((x,i)=><a key={x} href={["#about","#experience","#expertise","#projects","#contact"][i]}>{x}</a>)}</nav><div className="headerTools"><div className="languages" aria-label="Language">{(["tj","ru","en"] as Lang[]).map(x=><button key={x} className={lang===x?"active":""} onClick={()=>choose(x)}>{x.toUpperCase()}</button>)}</div><a className="talk" href="mailto:zamona08@gmail.com">{t.talk}</a></div></header>
    <section className="hero"><div className="heroText"><p className="eyebrow">{t.location}</p><h1>{t.title}</h1><div className="accent"/><p className="lead">{t.lead}</p><div className="actions"><a className="btn blue" href="#experience">{t.view} <b>→</b></a><a className="under" href="#contact">{t.contact}</a></div><div className="stats"><div><strong>1,350+</strong><span>{t.stats[0]}</span></div><div><strong>150+</strong><span>{t.stats[1]}</span></div><div><strong>50+</strong><span>{t.stats[2]}</span></div></div></div><Diagram/></section>
    <section className="section" id="about"><p className="kicker">{t.sections[0]}</p><div className="two"><h2>{t.profileTitle}</h2><div className="copy"><p>{t.profile[0]}</p><p>{t.profile[1]}</p><p className="available"><i/> {t.available}</p></div></div></section>
    <section className="section dark" id="experience"><p className="kicker">{t.sections[1]}</p><div className="exp"><span>{t.current}</span><div><p className="eyebrow">{t.operations}</p><h2>{t.scale}</h2><p>{t.expText}</p></div><ul>{t.expList.map(x=><li key={x}>{x}</li>)}</ul></div></section>
    <section className="section" id="expertise"><p className="kicker">{t.sections[2]}</p><div className="heading"><h2>{t.expertiseTitle}</h2><p>{t.expertiseText}</p></div><div className="skillGrid">{t.skills.map((s,i)=><article key={s[0]}><span>0{i+1}</span><h3>{s[0]}</h3><p>{s[1]}</p></article>)}</div><div className="tags">{["Ubuntu Linux","Docker","MikroTik","Headscale","Tailscale","Python","FastAPI","PostgreSQL","Redis","n8n","Ollama","RTSP / ONVIF"].map(x=><span key={x}>{x}</span>)}</div></section>
    <section className="section projects" id="projects"><p className="kicker">{t.sections[3]}</p>{t.projects.map((p,i)=><article key={p[0]}><span>0{i+1}</span><h3>{p[0]}</h3><p>{p[1]}</p><b>{p[2]}</b></article>)}</section>
    <section className="section enterprise"><p className="kicker">{t.sections[4]}</p><div className="two"><h2>{t.businessTitle}</h2><div className="copy"><p>{t.business[0]}</p><p>{t.business[1]}</p><div className="businessTags"><span>Own server</span><span>Websites</span><span>CCTV retail</span><span>Computers</span><span>Alif Shop</span><span>LakLak</span></div></div></div></section>
    <section className="section"><p className="kicker">{t.sections[5]}</p><div className="cards">{t.cards.map(c=><article key={c[0]}><small>{c[0]}</small><h3>{c[1]}</h3><p>{c[2]}</p></article>)}</div></section>
    <section className="contact" id="contact"><p className="eyebrow">{t.contactKicker}</p><h2>{t.contactTitle}</h2><p>{t.contactText}</p><div className="socials" aria-label="Contact Zafari Hakimjon"><a href="https://t.me/ZafarKarimovv" target="_blank" rel="noreferrer"><i>✈</i><span>Telegram</span></a><a href="https://wa.me/992878484808" target="_blank" rel="noreferrer"><i>WA</i><span>WhatsApp</span></a><a href="mailto:zamona08@gmail.com"><i>@</i><span>Email</span></a><a href="tel:+992878484808"><i>☎</i><span>{t.call}</span></a></div><a className="phoneNumber" href="tel:+992878484808">+992 878 48 48 08</a></section>
    <footer><a className="brand" href="#top">ZAFARI HAKIMJON</a><p>IT Infrastructure · DevOps · Network · AI</p><p>© 2026 Dushanbe, Tajikistan</p></footer>
  </main>;
}
